spring:

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tulip_erp
    username: postgres
    password: password
    hikari:
      max-lifetime: 600000
      connection-timeout: 5000
      maximum-pool-size: 50
      minimum-idle: 10
      leak-detection-threshold: 1200000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: SPRING_SESSION

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    org:
      apache:
        tomcat: ${logging.level.root}
        catalina: ${logging.level.root}
      hibernate:
        SQL: ${logging.level.root}
        type:
          descriptor:
            sql:
              BasicBinder: ${logging.level.root}